version: "3.7"

services:
  postgres:
    container_name: ${POSTGRES_SERVICE}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - 5444:5432
    volumes:
      - ./database:/database/
    networks:
      - dev

  postgres_admin:
    container_name: ${PG_SERVICE}
    image: dpage/pgadmin4:latest
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5050:80
    networks:
      - dev

volumes:
  database:

networks:
  dev:
    driver: bridge