version: "3.7"

services:
  postgres:
    container_name: ${POSTGRES_SERVICE}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - 5444:5432
    volumes:
      - ./database:/database/
    networks:
      - transcendence-network

  postgres_admin:
    container_name: ${PG_SERVICE}
    image: dpage/pgadmin4:latest
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5050:80
    networks:
      - transcendence-network

  frontend:
    container_name: ${FRONTEND_SERVICE}
    build: ./pong
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - transcendence-network
  
  backend:
    container_name: ${BACKEND_SERVICE}
    build: ./backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 3001:3001
    networks:
      - transcendence-network

volumes:
  database:

networks:
  transcendence-network:
    driver: bridge